// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        v3.19.4
// source: onlineConfService.proto

package onlineConf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ping          string                 `protobuf:"bytes,1,opt,name=ping,proto3" json:"ping,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_onlineConfService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_onlineConfService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_onlineConfService_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetPing() string {
	if x != nil {
		return x.Ping
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pong          string                 `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_onlineConfService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_onlineConfService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_onlineConfService_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetPong() string {
	if x != nil {
		return x.Pong
	}
	return ""
}

// GetServiceList 获取etcd注册的所有服务入参
type GetServiceListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   []string               `protobuf:"bytes,1,rep,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"` //服务名
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceListReq) Reset() {
	*x = GetServiceListReq{}
	mi := &file_onlineConfService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceListReq) ProtoMessage() {}

func (x *GetServiceListReq) ProtoReflect() protoreflect.Message {
	mi := &file_onlineConfService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceListReq.ProtoReflect.Descriptor instead.
func (*GetServiceListReq) Descriptor() ([]byte, []int) {
	return file_onlineConfService_proto_rawDescGZIP(), []int{2}
}

func (x *GetServiceListReq) GetServiceName() []string {
	if x != nil {
		return x.ServiceName
	}
	return nil
}

type GetServiceListArrays struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=serviceName,proto3" json:"serviceName,omitempty"` //活跃的服务名
	IpAddr        string                 `protobuf:"bytes,2,opt,name=ipAddr,proto3" json:"ipAddr,omitempty"`           //活跃的ip和端口
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`            //活跃机器
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceListArrays) Reset() {
	*x = GetServiceListArrays{}
	mi := &file_onlineConfService_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceListArrays) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceListArrays) ProtoMessage() {}

func (x *GetServiceListArrays) ProtoReflect() protoreflect.Message {
	mi := &file_onlineConfService_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceListArrays.ProtoReflect.Descriptor instead.
func (*GetServiceListArrays) Descriptor() ([]byte, []int) {
	return file_onlineConfService_proto_rawDescGZIP(), []int{3}
}

func (x *GetServiceListArrays) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *GetServiceListArrays) GetIpAddr() string {
	if x != nil {
		return x.IpAddr
	}
	return ""
}

func (x *GetServiceListArrays) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// GetServiceList 获取etcd注册的所有服务出参
type GetServiceListResp struct {
	state                protoimpl.MessageState  `protogen:"open.v1"`
	GetServiceListArrays []*GetServiceListArrays `protobuf:"bytes,1,rep,name=get_service_list_arrays,json=getServiceListArrays,proto3" json:"get_service_list_arrays,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetServiceListResp) Reset() {
	*x = GetServiceListResp{}
	mi := &file_onlineConfService_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceListResp) ProtoMessage() {}

func (x *GetServiceListResp) ProtoReflect() protoreflect.Message {
	mi := &file_onlineConfService_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceListResp.ProtoReflect.Descriptor instead.
func (*GetServiceListResp) Descriptor() ([]byte, []int) {
	return file_onlineConfService_proto_rawDescGZIP(), []int{4}
}

func (x *GetServiceListResp) GetGetServiceListArrays() []*GetServiceListArrays {
	if x != nil {
		return x.GetServiceListArrays
	}
	return nil
}

var File_onlineConfService_proto protoreflect.FileDescriptor

var file_onlineConfService_proto_rawDesc = []byte{
	0x0a, 0x17, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x6f, 0x6e, 0x6c, 0x69, 0x6e,
	0x65, 0x43, 0x6f, 0x6e, 0x66, 0x72, 0x70, 0x63, 0x22, 0x1d, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x70, 0x69, 0x6e, 0x67, 0x22, 0x1e, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x70, 0x6f, 0x6e, 0x67, 0x22, 0x36, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x21, 0x0a, 0x0c,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22,
	0x66, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4c, 0x69, 0x73,
	0x74, 0x41, 0x72, 0x72, 0x61, 0x79, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x70, 0x41,
	0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x70, 0x41, 0x64, 0x64,
	0x72, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x70, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x5a, 0x0a,
	0x17, 0x67, 0x65, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x6c, 0x69, 0x73,
	0x74, 0x5f, 0x61, 0x72, 0x72, 0x61, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23,
	0x2e, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x72, 0x70, 0x63, 0x2e, 0x47,
	0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x72, 0x72,
	0x61, 0x79, 0x73, 0x52, 0x14, 0x67, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4c,
	0x69, 0x73, 0x74, 0x41, 0x72, 0x72, 0x61, 0x79, 0x73, 0x32, 0x9f, 0x01, 0x0a, 0x0d, 0x4f, 0x6e,
	0x6c, 0x69, 0x6e, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x52, 0x70, 0x63, 0x12, 0x37, 0x0a, 0x04, 0x50,
	0x69, 0x6e, 0x67, 0x12, 0x16, 0x2e, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x43, 0x6f, 0x6e, 0x66,
	0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x6f, 0x6e,
	0x6c, 0x69, 0x6e, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x55, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x20, 0x2e, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x43,
	0x6f, 0x6e, 0x66, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x21, 0x2e, 0x6f, 0x6e, 0x6c, 0x69, 0x6e,
	0x65, 0x43, 0x6f, 0x6e, 0x66, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x42, 0x0e, 0x5a, 0x0c, 0x2e,
	0x2f, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_onlineConfService_proto_rawDescOnce sync.Once
	file_onlineConfService_proto_rawDescData = file_onlineConfService_proto_rawDesc
)

func file_onlineConfService_proto_rawDescGZIP() []byte {
	file_onlineConfService_proto_rawDescOnce.Do(func() {
		file_onlineConfService_proto_rawDescData = protoimpl.X.CompressGZIP(file_onlineConfService_proto_rawDescData)
	})
	return file_onlineConfService_proto_rawDescData
}

var file_onlineConfService_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_onlineConfService_proto_goTypes = []any{
	(*Request)(nil),              // 0: onlineConfrpc.Request
	(*Response)(nil),             // 1: onlineConfrpc.Response
	(*GetServiceListReq)(nil),    // 2: onlineConfrpc.GetServiceListReq
	(*GetServiceListArrays)(nil), // 3: onlineConfrpc.GetServiceListArrays
	(*GetServiceListResp)(nil),   // 4: onlineConfrpc.GetServiceListResp
}
var file_onlineConfService_proto_depIdxs = []int32{
	3, // 0: onlineConfrpc.GetServiceListResp.get_service_list_arrays:type_name -> onlineConfrpc.GetServiceListArrays
	0, // 1: onlineConfrpc.OnlineConfRpc.Ping:input_type -> onlineConfrpc.Request
	2, // 2: onlineConfrpc.OnlineConfRpc.GetServiceList:input_type -> onlineConfrpc.GetServiceListReq
	1, // 3: onlineConfrpc.OnlineConfRpc.Ping:output_type -> onlineConfrpc.Response
	4, // 4: onlineConfrpc.OnlineConfRpc.GetServiceList:output_type -> onlineConfrpc.GetServiceListResp
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_onlineConfService_proto_init() }
func file_onlineConfService_proto_init() {
	if File_onlineConfService_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_onlineConfService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_onlineConfService_proto_goTypes,
		DependencyIndexes: file_onlineConfService_proto_depIdxs,
		MessageInfos:      file_onlineConfService_proto_msgTypes,
	}.Build()
	File_onlineConfService_proto = out.File
	file_onlineConfService_proto_rawDesc = nil
	file_onlineConfService_proto_goTypes = nil
	file_onlineConfService_proto_depIdxs = nil
}
