// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: onlineConfService.proto

package server

import (
	"context"

	"zero-online-conf/rpc/internal/logic"
	"zero-online-conf/rpc/internal/svc"
	"zero-online-conf/rpc/onlineConf"
)

type OnlineConfRpcServer struct {
	svcCtx *svc.ServiceContext
	onlineConf.UnimplementedOnlineConfRpcServer
}

func NewOnlineConfRpcServer(svcCtx *svc.ServiceContext) *OnlineConfRpcServer {
	return &OnlineConfRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *OnlineConfRpcServer) Ping(ctx context.Context, in *onlineConf.Request) (*onlineConf.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}

// GetServiceList 获取etcd注册的所有服务
func (s *OnlineConfRpcServer) GetServiceList(ctx context.Context, in *onlineConf.GetServiceListReq) (*onlineConf.GetServiceListResp, error) {
	l := logic.NewGetServiceListLogic(ctx, s.svcCtx)
	return l.GetServiceList(in)
}
