// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type LoginReq struct {
	UserName string `json:"userName"`
	Password string `json:"password"`
}

type LoginResp struct {
	UserName string `json:"userName"`
	Token    string `json:"token"`
}

type Response struct {
	Message string `json:"message"`
}
