// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type GetServiceListArrays struct {
	ServiceName string `json:"serviceName"`
	IpAddr      string `json:"ipAddr"`
}

type GetServiceListReq struct {
	ServiceName []string `json:"serviceName"`
}

type GetServiceListResp struct {
	GetServiceListArrays []*GetServiceListArrays `json:"getServiceListArrays"`
}

type Header struct {
	AccessToken string `header:"access-token,optional"` // Access Token
	Uid         string `header:"uid,optional"`          // Uid
}

type LoginReq struct {
	UserName string `json:"userName"`
	Password string `json:"password"`
}

type LoginResp struct {
	UserName string `json:"userName"`
	UserId   int64  `json:"userId"`
	Token    string `json:"token"`
}

type Response struct {
	Message string `json:"message"`
}
