// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	"zero-online-conf/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 获取新的公钥和私钥
				Method:  http.MethodGet,
				Path:    "/generateRSAKey",
				Handler: GenerateRSAKeyHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/ping",
				Handler: PingHandler(serverCtx),
			},
			{
				// 用户登录
				Method:  http.MethodPost,
				Path:    "/user/v1/userLogin",
				Handler: UserLoginHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					// ListHandler 展示所有配置的列表
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: ListHandler(serverCtx),
				},
				{
					// 获取服务注册列表
					Method:  http.MethodPost,
					Path:    "/v1/getServiceList",
					Handler: GetServiceListHandler(serverCtx),
				},
			}...,
		),
	)
}
